### ISSUE TITLE
How to provide multiple languages support?

### ISSUE THREAD

**Issue by xhe** [BoilerplateMVC/Marionette-Require-Boilerplate#17]
This boilerplate is amazing, thanks.
I now have a question, how to change language, if I want to load Chinese, what will be a good solution to use i18n support in hbs?
Thanks

**Comment by charlieongithub** [comment]
Hi,

You can easily implement i18next module. I have used similar solution in one of my Backbone projects.

This is a node.js module if you need it on the server side (i.e. for email-templates): https://www.npmjs.com/package/i18next

Client side documentation: http://i18next.github.io/i18next/

Then just write a helper to use in your .hbs files.

K

**Comment by brettjonesdev** [comment]
Good suggestion from @charlieongithub, closing.
